export const IPC = {
  bootstrap: "bootstrap:state",
  sessions: {
    list: "sessions:list",
    load: "sessions:load",
    create: "sessions:create",
    save: "sessions:save",
    event: "sessions:event",
    takeoverLock: "sessions:takeover-lock",
  },
  settings: { save: "settings:save" },
  appQuit: "app:quit",
  agent: {
    start: "agent:start",
    abort: "agent:abort",
    approvalResponse: "agent:approval-response",
    askResponse: "agent:ask-response",
    token: "agent:token",
    assistantTurnEnd: "agent:assistant-turn-end",
    toolStart: "agent:tool-start",
    toolEnd: "agent:tool-end",
    approvalRequest: "agent:approval-request",
    askRequest: "agent:ask-request",
    done: "agent:done",
    status: "agent:status",
    quota: "agent:quota",
    error: "agent:error",
  },
} as const;
